<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="NServiceBus" Version="9.*" />
    <PackageReference Include="NServiceBus.Extensions.Hosting" Version="3.*" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\NServiceBusEndpoint\NServiceBusEndpoint.csproj" />
  </ItemGroup>

</Project>
